  build-and-push:
    needs: build-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker images
        run: |
          set -e
          for d in api-gateway auth product order; do
            if [ -f "$d/Dockerfile" ]; then
              IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/$d:latest
              echo "Building and pushing $IMAGE_NAME"
              docker build -t $IMAGE_NAME $d
              docker push $IMAGE_NAME
            fi
          done

      - name: ✅ Pull latest Docker images after push
        run: |
          set -e
          for d in api-gateway auth product order; do
            IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/$d:latest
            echo "Pulling latest image for $d"
            docker pull $IMAGE_NAME
          done

      # (Optional) nếu bạn muốn CI/CD tự chạy container sau khi pull
      - name: 🚀 Run containers (optional)
        run: |
          for d in api-gateway auth product order; do
            IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/$d:latest
            echo "Running container for $d"
            docker run -d --name $d -p 3000:3000 $IMAGE_NAME || true
          done
