name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies for all services
        run: |
          set -e
          for d in api-gateway auth product order; do
            if [ -f "$d/package.json" ]; then
              echo "Installing deps for $d"
              (cd $d && npm ci || npm install)
            fi
          done

      - name: Run tests for services that have tests
        run: |
          set -e
          for d in auth product; do
            if [ -f "$d/package.json" ]; then
              echo "Running tests for $d"
              (cd $d && npm test --silent)
            fi
          done

  build-and-push:
    needs: build-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/my-app:${{ github.sha }} .
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-app:${{ github.sha }}