name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Cài dependencies cho từng service
      - name: Install dependencies for Auth service
        run: |
          cd auth
          npm ci
          cd ..

      - name: Install dependencies for Product service
        run: |
          cd product
          npm ci
          cd ..

      - name: Install dependencies for Order service
        run: |
          cd order
          npm ci
          cd ..

      # (Thêm service khác nếu có)
      # - name: Install dependencies for Payment service
      #   run: |
      #     cd payment
      #     npm ci
      #     cd ..

      - name: Run tests
        run: |
          npm test --silent || echo "No test scripts defined"

  build-and-push:
    needs: build-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/my-app:${{ github.sha }} .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-app:${{ github.sha }}
